### ISSUE TITLE
(tiny-react): hydration error with empty string

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/js-utils#188]
There's no text node when rendered empty on SSR.
Probably we can check this case during hydration hydration and workaround without extra ssr comment etc...?

## repro

```tsx
export function App() {
  return <div>{""}</div>
}
```

## error log on client

```
@hiogawa_tiny-react.js?v=af88bd93:391 Uncaught Error: text hydration mismatch (actual: 'undefined', expected: '#text')
    at hydrateNode (@hiogawa_tiny-react.js?v=af88bd93:391:5)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:215:13)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:233:21)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:329:21)
    at render (@hiogawa_tiny-react.js?v=af88bd93:198:20)
    at hydrate (@hiogawa_tiny-react.js?v=af88bd93:210:10)
    at main (client.ts:8:3)
    at client.ts:11:1
```

**Comment by hi-ogawa** [comment]
It could be a different bug but this also doesn't work...

```tsx
export function App() {
  return <div>hi {"abc"}</div>
}
```

```
@hiogawa_tiny-react.js?v=af88bd93:395 Uncaught Error: text hydration mismatch (actual: 'hi abc', expected: 'hi ')
    at hydrateNode (@hiogawa_tiny-react.js?v=af88bd93:395:5)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:215:13)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:312:22)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:233:21)
    at reconcileNode (@hiogawa_tiny-react.js?v=af88bd93:329:21)
    at render (@hiogawa_tiny-react.js?v=af88bd93:198:20)
    at hydrate (@hiogawa_tiny-react.js?v=af88bd93:210:10)
    at main (client.ts:8:3)
    at client.ts:11:1
```
